apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - nats.yaml
  - gobmp-nats.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

# Override the image tag here for each environment, e.g.:
# images:
#   - name: syd
#     newName: ghcr.io/jalapeno/syd
#     newTag: "0.1.0"
